spring:
  config:
    activate:
      on-profile: default
      
external:
  service-foo: 
    endpoint: https://moary04-net-conn-api-gateway.private.azuremicroservices.io
  service-bar: 
    endpoint: https://moary04-net-conn2-api-gateway.private.azuremicroservices.io
