spring:
  config:
    activate:
      on-profile: default
      
other:
  service: https://moary04-net-conn-api-gateway.private.azuremicroservices.io
  service2: https://moary04-net-conn2-api-gateway.private.azuremicroservices.io
