spring:
  config:
    activate:
      on-profile: default
      
external:
  service-foo: 
    endpoint: https://moary06-net-conn-east-us-api-gateway.private.azuremicroservices.io
  service-bar: 
    endpoint: https://moary06-net-conn-west-us-api-gateway.private.azuremicroservices.io
